export enum Template {
  STORY = "STORY",
  POST = "POST",
  GALLERY = "GALLERY",
  PORTAIT_THUMBNAIL = "PORTAIT_THUMBNAIL",
  LANDSCAPE_THUMBNAIL = "LANDSCAPE_THUMBNAIL",
  PORTRAIT = "PORTRAIT",
  LANDSCAPE = "LANDSCAPE",
  TEMPLATE_PROCESSING = "TEMPLATE_PROCESSING",
}
