import type { Metadata } from "next";
import { css } from "@/styled-system/css"
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <div className={css({
            maxWidth: "960px",
            my: 10,
            mx: 4,
            md: {
              mx: "auto"
            }
          })}>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
